### ISSUE TITLE
Move to GitHub Actions

### ISSUE THREAD

**Issue by tdowrick** [UCL/scikit-surgerycalibration#15]

**Comment by tdowrick** [comment]
@thompson318 Are you happy if we merge this to master and remove travis?

**Comment by thompson318** [comment]
@tdowrick Why did you stop using tox?

**Comment by tdowrick** [comment]
I realised that it is tricky to use tox and to test with different version of python.

On GitLab runners, we had different versions of python installed locally, which tox can then be able to access. Here, we specify a single version of python per instance on the VM, so if tox trys to run 3.7 on a 3.6 VM it will fail. I'm not sure if there is a sensible way around this?

**Comment by thompson318** [comment]
Yes, I had the same problem with travis. I don't there's an easy way round it. So yes, please merge it and remove travis.
