### ISSUE TITLE
Command line app for Video Calibration, nominally for BARD.

### ISSUE THREAD

**Issue by MattClarkson** [UCL/scikit-surgerycalibration#18]

**Comment by MattClarkson** [comment]
Hi @thompson318 , can you take a quick look at branch 18-video-calib-app.
I think it will do for now, and provide some nice functionality for BARD, and can be expanded going forward.
In addition to enabling a single user to calibrate with their phone (just search google images for a chessboard, and put the parameters in the config file), it also shows the points that were detected, and updates the calibration with each new captured image.
Should be enough?
M

**Comment by thompson318** [comment]
Something slightly amis with the command line parser, I started with this;

python sksVideoCalibration.py -c config/video_chessboard_conf.json 
Traceback (most recent call last):
  File "sksVideoCalibration.py", line 8, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/thompson/data/scikit-surgerycalibration/sksurgerycalibration/ui/video_calibration_command_line.py", line 42, in main
    run_video_calibration(args.config, args.save, args.prefix)
  File "/home/thompson/data/scikit-surgerycalibration/sksurgerycalibration/ui/video_calibration_app.py", line 30, in run_video_calibration
    raise ValueError("If you provide -p/--prefix, "
ValueError: If you provide -p/--prefix, you must provide -s/--save

**Comment by thompson318** [comment]
Once I set -s it works well for me. Nice work.
